sudo: required

services:
- docker

script:
- make build test

after_success:
- make coverage
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: uOHz6QPbvIPKgMVDbyIMmVRYJvM2eeCMc7yVf7g32OogyJLU8jyUiEAO5cqUVO2jp0I++QQH9BtsTYdJ7O9dR1a/xz+R7Aua//lalDBD72R8jMI0h8DY7ywl4ff4G9kpcSqn5FjtHSS1Ld1sZF/pO4epVyRfEX096iuq4w8Qaeuv8DaBPivXaKuHDCSFLXJlOrI/F/vnOarhyt9mqkVuRBE8tWtumWTgliCosBf83l4/asoI7TUmZu4fAYHmoHdbPhoAIUzwKOZQM6CxwEwObi56MGA7SyAUVy1+QuMmymjdH4t3n7Z9WdRZgI6wHK+TN44D+v6ygYtamMHkv5wCqd47agnda7qIbXpDmgPqN52bqyh+aAVoQJH/gLomGDQux5Cw9eY2yGEaQwPq5SrAr8xPH9GfxSTOH8OOLcvfrI4k5LU1Kk8szJEtMiVARnIwanCwiQhmNKYhyi0f1Sp3W9hd+O2chWvfARhQFR/nxdEFeBIqSftG2uIilx0dIl3Z7svyQIcwEw7plAC+fVcZ2n4SN/hPi80z1Cs64qMlqmMm8J45uDJlvL/IOJ6rY7846mty3n6NEKMq9bWb6tyKyhNgARv0BToE1Xj9hiY1D33RKw60SSxzrluVoDz+wYerv550peOzoP2XRBedoyCsxKLCTaB/rWzBmFtQV+r7xwQ=
  on:
    tags: true
    repo: hmcts/one-per-page
