sudo: required

services:
  - docker

script:
  - make build test

after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: michael@allen.digital
  api_key:
    secure: cp3aRJW5ht/jVbz/hBXlmd1r0g6B1k+crEIle8KVavh+4Qd0Y6SSe85HJvHmeJmjQoV/yC0l9klTkorSWx+Jg9CIwkRev/jrchKvGjWhn3nsfrL73L5YKCAPaYAQnQSnydpnOGkzjoWS/7Px0Lm3Dl4TUxwcKsI/IcHpzCj56Vam8iVuH/l8EmO678BJcgCcbsionJOYttOmKMSaUdXYLrnLhX2Valu5ZPAP2/wdeRT0L3D3NZJHiReXJ1DVHvJkpSjs5pD4tE5MzRDDW/8Z12bPfR3AbYEYC1Ri8lhNom3YWMzIumlsO8LElllcVmxkxVHQkWIIY7gOUq/25gyx534FJ8S297LYhqWh7vULxyh+/GQEe3oHYUUFod3GOQRAqytwSIFnL6gQMjJL2bGrt1firxZhEhj3oTPm+FFSe6jzXQkbRBUNKYXofra2ONKueA2wwVaVoT2XKtG+T84SlkrcokHGEcycZgP9NSJfc7+hwWdgPkC1p/e9g/omhw2j+qmEL4p35D4/Fr5CzUVuvGmvjmXEznjxxb1jTYp7pzMIgcWXoYQeNba1xjS4Zg4JgpIxpNsxKBuHySQmMhNia3KdZG/xjBPCRnc1+eMAfAF7X586rzJIcZVHEmSMxceqy7OWQrbdw4xCR++UPhvsucHUlEoy9H5TqSHx05FnUQA=
  on:
    tags: true
    repo: hmcts/one-per-page
