version: '2.1'

services:
  dev:
    container_name: one-per-page
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - ../look-and-feel:/usr/src/look-and-feel
    ports:
      - "9229:9229"
      - "3000:3000"
    environment:
      REDIS_URL: 'redis://redis:6379'
    links:
      - redis

  redis:
    image: redis
