version: '2.1'

services:
  dev:
    container_name: one-per-page
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - "9229:9229"
      - "3000:3000"
    links:
      - redis

  redis:
    image: redis
    expose:
      - 6789
